// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Waifu.Data;

#nullable disable

namespace Waifu.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240115150150_SettingsAndModel")]
    partial class SettingsAndModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Waifu.Models.ChatChannel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("channels");
                });

            modelBuilder.Entity("Waifu.Models.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ChatChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Sender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SentByUser")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChatChannelId");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("Waifu.Models.LocalLlamaModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("models");
                });

            modelBuilder.Entity("Waifu.Models.RoleplayCharacter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePictureHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SampleMessages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("characters");
                });

            modelBuilder.Entity("Waifu.Models.Settings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SettingsTarget")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TargetModelId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<int>("TopK")
                        .HasColumnType("INTEGER");

                    b.Property<float>("TopP")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TargetModelId");

                    b.ToTable("settings");
                });

            modelBuilder.Entity("Waifu.Models.ChatChannel", b =>
                {
                    b.HasOne("Waifu.Models.RoleplayCharacter", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Waifu.Models.ChatMessage", b =>
                {
                    b.HasOne("Waifu.Models.ChatChannel", "ChatChannel")
                        .WithMany()
                        .HasForeignKey("ChatChannelId");

                    b.Navigation("ChatChannel");
                });

            modelBuilder.Entity("Waifu.Models.Settings", b =>
                {
                    b.HasOne("Waifu.Models.LocalLlamaModel", "TargetModel")
                        .WithMany()
                        .HasForeignKey("TargetModelId");

                    b.Navigation("TargetModel");
                });
#pragma warning restore 612, 618
        }
    }
}
