using Waifu.Models;

namespace Waifu;

public interface IChatHandler
{
    /// <summary>
    /// When the message is generated by the other party.
    /// </summary>
    event EventHandler<string> CompleteMessageGenerated;

    event EventHandler<string> PartialMessageGenerated;

    public ChatChannel ChatChannel { get; set; }

    Task InitializeAsync();

    Task<string?> SendMessageAndGetResultAsync(ChatMessage message);
}